Update pre-commit hook

diff --git a/automation/scripts/pre-commit-windows b/automation/scripts/pre-commit-windows
--- a/automation/scripts/pre-commit-windows
+++ b/automation/scripts/pre-commit-windows
@@ -6,10 +6,6 @@ echo "Running lint check..."
 
 status=$?
 
-if [ "status" = 0 ] ; then
-  echo "No formatting issues were found"
-  exit 0
-else
-  echo 1>&2 "* There are code formatting issue that must be addressed"
-  exit 1
-fi
+# return 1 exit code if running checks fails
+[ $status -ne 0 ] && exit 1
+exit 0
